# Generated by Django 5.1.4 on 2025-01-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_profissional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profissional',
            name='area_atuacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
